server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          zk-nodes: localhost
    bus:
      trace:
        enabled: true